apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: {{.Release.Namespace}}
  labels:
    app: emojivoto
spec:
  ports:
  - name: {{ .Values.proto.grpc }}
    port: 8080
    targetPort: 8080
  - name: {{ .Values.proto.prom }}
    port: 8801
    targetPort: 8801
  selector:
    app: emoji-svc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: {{.Release.Namespace}}
  labels:
    app: emojivoto
spec:
  ports:
  - name: {{ .Values.proto.grpc }}
    port: 8080
    targetPort: 8080
  - name: {{ .Values.proto.prom }}
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: {{.Release.Namespace}}
  labels:
    app: emojivoto
spec:
  ports:
  - name: {{ .Values.proto.http }}
    port: 80
    targetPort: 8080
  selector:
    app: web-svc
  type: ClusterIP
