apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: binaries
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
