apiVersion: batch/v1
kind: Job
metadata:
  name: download-terraform
  namespace: {{.Release.Namespace}}
spec:
  template:
    metadata:
      labels:
        pvc: binaries
    spec:
      restartPolicy: OnFailure
      containers:
      - name: download-terraform
        image: hashicorp/terraform:{{.Values.terraform.version}}
        command:
        - sh
        args:
        - -c
        - 'mv /bin/terraform /binaries'
        volumeMounts:
        - name: binaries
          mountPath: /binaries
      serviceAccountName: downloader
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: pvc
                operator: In
                values:
                - binaries
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: binaries
        persistentVolumeClaim:
          claimName: binaries
