apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobrunner
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: downloader
  namespace: {{.Release.Namespace}}
