apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
  name: {{ .Release.Name }}-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-agent
    namespace: {{ .Release.Namespace }}
